[web]
host = "127.0.0.1"
port = 8080

[server.socket]
host = "0.0.0.0"
port = 6657

[server.websocket]
host = "0.0.0.0"
port = 6658

[database.redis.local]
host = "127.0.0.1"
port = 6379
important = 0
